### ISSUE TITLE
Problem with build on Win7/64bit

### ISSUE THREAD

**Issue by arc12** [antonycourtney/tad#120]
I worked through the steps in the readme + installed `npm install --global windows-build-tools` to get the VCBuild.exe (for `npm run electron-rebuild`)

managed to create a Tad Setup exe file which seems to run and prompts for a file to open but then shows an Error box
Error initialising Tad
T.default.driver.import is not a function

Executing from the installed shortcut produces the same error message.

Version installed from the downloaded exe works fine.

**Comment by arc12** [comment]
Followed the build process carfully, on a clean git clone.
Stack trace:
$ npm start csv/bart-comp-all.csv

> tad@0.8.5 start C:\Users\adam.cooper\Documents\Forks\tad
> electron . "csv/bart-comp-all.csv"


Wait for app ready
[23:00:45.220] [warn] Tad started, argv:  [ 'C:\\Users\\adam.cooper\\Documents\\Forks\\tad\\node_modules\\electron\\dist\\electron.exe',
  '.',
  'csv/bart-comp-all.csv' ]
[23:00:45.430] [info] postInstallCheck: looking for install marker file  C:\Users\adam.cooper\AppData\Roaming\Tad\install-marker-0_8_5.txt
[23:00:45.430] [info] postInstalCheck: found marker file, skipping post-install setup
[23:00:46.315] [error] caught error during fastImport:  TypeError: _sqlite2.default.driver.import is not a function
    at C:\Users\adam.cooper\Documents\Forks\tad\build\webpack:\src\csvimport.js:508:5
    at dbImport (C:\Users\adam.cooper\Documents\Forks\tad\build\webpack:\src\csvimport.js:507:10)
    at _callee3$ (C:\Users\adam.cooper\Documents\Forks\tad\build\webpack:\src\csvimport.js:546:25)
    at tryCatch (C:\Users\adam.cooper\Documents\Forks\tad\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\adam.cooper\Documents\Forks\tad\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\adam.cooper\Documents\Forks\tad\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\adam.cooper\Documents\Forks\tad\build\webpack:\~\babel-runtime\helpers\asyncToGenerator.js:17:1)
    at C:\Users\adam.cooper\Documents\Forks\tad\build\webpack:\~\babel-runtime\helpers\asyncToGenerator.js:28:1
    at process._tickCallback (internal/process/next_tick.js:103:7)
 TypeError: _sqlite2.default.driver.import is not a function
    at C:\Users\adam.cooper\Documents\Forks\tad\build\webpack:\src\csvimport.js:508:5
    at dbImport (C:\Users\adam.cooper\Documents\Forks\tad\build\webpack:\src\csvimport.js:507:10)
    at _callee3$ (C:\Users\adam.cooper\Documents\Forks\tad\build\webpack:\src\csvimport.js:546:25)
    at tryCatch (C:\Users\adam.cooper\Documents\Forks\tad\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\adam.cooper\Documents\Forks\tad\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\adam.cooper\Documents\Forks\tad\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\adam.cooper\Documents\Forks\tad\build\webpack:\~\babel-runtime\helpers\asyncToGenerator.js:17:1)
    at C:\Users\adam.cooper\Documents\Forks\tad\build\webpack:\~\babel-runtime\helpers\asyncToGenerator.js:28:1
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by antonycourtney** [comment]
Can't say with certainty, but what looks suspicious here is _sqlite2, when one of Tad's dependencies is a fork of node-sqlite3.
My only suggestion is to dig in to node_modules and confirm that the fork of node-sqlite3 built correctly (note that it includes compiled C++ code).

**Comment by robbyki** [comment]
@arc12  Were you able to make any progress with this? Having same issue but have not been able to determine a solution.

**Comment by oisin** [comment]
Having the same issue myself, on MacOS 10.13.3, node/npm versions as recommended.

**Comment by arc12** [comment]
no I failed!
I tried to start everything from the beginning again (but on the same PC) but no progress.

I was actually just trying to add in code to keep as strings any columns with numerical content but leading zeros; this is a common identifier format and typing as integers isnt right...

**Comment by antonycourtney** [comment]
Enough of you got bit by this that I rolled up my sleeves to investigate...

Should be fixed by 5adb5ef0522844c64488b31e8a0413d707b1ac73.

To apply the fix when building from source:
1. Do a `git pull` to update `master` to `HEAD`.
2. `rm -rf node_modules` to get rid of old installed package state.
3. Follow the instructions in [src/doc/building.md](https://github.com/antonycourtney/tad/blob/master/src/doc/building.md), starting from `npm install`

...and that should work.

## What happened:

Tad depends on a package called `sqlite` that, confusingly, depends on a package called `sqlite3`.
Tad includes a fork of `sqlite3` that includes C++ code for fast import of CSV files.
The version number of `sqlite` in `package.json` wasn't pinned, and a new version of `sqlite` was released that depended on a later version of `sqlite3` than is provided in the Tad fork.
Quick interim is just to pin `sqlite` to the specific version used to build Tad.

Hope that helps. A comment here letting me know if that resolves the issue for you would be appreciated.

**Comment by oisin** [comment]
🚀  Success for me -- pinned the version of sqlite in the package.json of my own fork and re-built from nam install as you suggested, successfully ran the build and loaded the sample CSV file. Much appreciated fix, thanks!

**Comment by antonycourtney** [comment]
Lovely, thanks for confirming @oisin! Closing....
