### ISSUE TITLE
Error: Unknown operator: ENDS

### ISSUE THREAD

**Issue by vuod** [antonycourtney/tad#133]
Tested with Linux Mint 19.1 (tad_0.9.0_amd64.deb) and Fedora 29 (tad-0.9.0.x86_64.rpm)

Filter
Column...
ends with
Apply

Tad window turned white and become inaccessible.

```
[14:33:25.248] [info] getRowCount: evaluated query in 0s 2.974015ms
(node:3129) UnhandledPromiseRejectionWarning: Error: Unknown operator: ENDS
    at constructor (/opt/Tad/resources/app.asar/build/webpack:/src/reltab.js:201:3)
    at A.toSqlWhere (/opt/Tad/resources/app.asar/build/webpack:/src/reltab.js:216:5)
    at e.opArgs.map.e (/opt/Tad/resources/app.asar/build/webpack:/src/reltab.js:336:8)
    at Array.map (<anonymous>)
    at j.toSqlWhere (/opt/Tad/resources/app.asar/build/webpack:/src/reltab.js:332:5)
    at groupBy (/opt/Tad/resources/app.asar/build/webpack:/src/reltab.js:918:14)
    at kind (/opt/Tad/resources/app.asar/build/webpack:/src/reltab.js:1077:18)
    at message (/opt/Tad/resources/app.asar/build/webpack:/src/reltab.js:1091:16)
    at F.ConstVal [as toCountSql] (/opt/Tad/resources/app.asar/build/webpack:/src/reltab.js:486:3)
    at Object.rowCount (/opt/Tad/resources/app.asar/build/webpack:/src/reltab-sqlite.js:69:16)
(node:3129) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3129) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by antonycourtney** [comment]
Clearly a bug. Thanks for reporting.
