### ISSUE TITLE
Uncaught Exception:

### ISSUE THREAD

**Issue by sandiprb** [antonycourtney/tad#73]
OS: Ubuntu 14.04

```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.Mrihtc)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/Tad/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Object.<anonymous> (/opt/Tad/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:190:3)
```

**Comment by julienbalas** [comment]
same issue on debian 8
$lsb_release -d
Description:	Debian GNU/Linux 8.7 (jessie)

$uname -a
Linux computer 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

**Comment by finelli** [comment]
confirmed - same error message - with a recent .deb (0.8.5) and slightly newer software:

1. Description:	Debian GNU/Linux 8.10 (jessie)
2. Linux server 4.9.0-0.bpo.2-amd64 #1 SMP Debian 4.9.18-1~bpo8+1 (2017-04-10) x86_64 GNU/Linux
3. ldd (Debian GLIBC 2.19-18+deb8u10) 2.19
